source 'https://bitbucket.org/mpymnt/io.mpymnt.repo.pods.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

target :"mpos-ui"

target :"mpos-ui.podsdummy" do

  pod 'payworks/mpos/core',         '2.13.0'
  pod 'CocoaLumberjack',            '~> 2.0.0'
  pod 'MPBSignatureViewController', '~> 1.5.1'
  pod 'Lockbox',                    '~> 2.1.0'

end


post_install do |installer|

    installer.pods_project.targets.each do |target|

        target.build_configurations.each do |config|

            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['CLANG_MODULES_AUTOLINK'] = 'NO'
	
        end
    end
    puts("[X] Enabled always building all architectures [ONLY_ACTIVE_ARCH]")
    puts("[X] Deactivated autolinking of frameworks/modules [CLANG_MODULES_AUTOLINK]")
end
