source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/mpymnt/io.mpymnt.repo.pods.git'

pod 'AFNetworking', 				        '2.5.4'
pod 'CocoaLumberjack',              '~> 2.0'
pod 'MPBSignatureViewController',   '~> 1.4.11'
pod 'Toast',                        '~> 2.4'
pod 'Lockbox',                      '~> 2.1.0'