source 'https://bitbucket.org/mpymnt/io.mpymnt.repo.pods.git'
source 'https://github.com/CocoaPods/Specs.git'


target :"mpos-ui-sample" do

  pod 'payworks',                     '2.13.0'

  pod 'CocoaLumberjack',              '~> 2.0'
  pod 'MPBSignatureViewController',   '~> 1.5.1'
  pod 'Toast',                        '~> 2.4'
  pod 'Lockbox',                      '~> 2.1.0'

end
